const BACKEND_URLS = {
  baseURL: import.meta.env.VITE_APP_BACKEND_BASE_URL,
  // baseURL: "https://dummyjson.com",
  auth: {
    me: "/profile",
    login: "/auth/login",
    refreshToken: "/auth/refresh",
    forgotPassword: "/auth/forgot-password/",
    resetPassword: "/auth/reset-password/",
    logout: "/auth/logout",
  },
  profile: {
    changePassword: "/profile/change-password",
    updateProfile: "/profile",
    update2fa: "/profile/toggle-2fa",
  },
  admin: {
    createAdmin: "/admins",
    getAdmins: "/admins",
  },
  crypto: "/crypto-transactions",
  giftcard: "/giftcard-transactions",
  transaction: "/transactions/services",
  wallet: "/transactions/wallet",
  annoucement: "/alerts",
  banners: "/banners",
  referralTerms: "/referral-terms",
  systemAccount: "/bank-accounts",
  providers: "/providers",
  service: "/services",
  product: "/products",
  service_types: "/service-types",
  discounts: "/discounts",
  giftcard_categories: "/giftcard-categories",
  giftcard_product: "/giftcard-products",
  crypto_network: "crypto/networks",
  crypto_assets: "/crypto",
  // product: {
  //   all: "/products",
  //   productReview: "/review",
  // },
  stores: "/store",
  catalog: {
    brands: "/catalog/brands",
    categories: "/catalog/categories",
    subcategories: "/catalog/sub-categories",
    colors: "/catalog/colors",
  },
  orders: "/orders",
  generalOrders: "/order-summary",
  coupons: "/coupon",
  users: "/users",
  roles: "/roles",
  permissions: "/roles/permissions",
  serviceCharge: "/additional-charges",
  shipping: {
    intlZones: "/shipping-zone",
    intlZonesWeight: "/shipping-zone-weight",
    intlClass: "/shipping-class",
    localZones: "/local-shipping-zone",
    localZonesWeight: "/local-shipping-zone-weight",
    localClass: "/local-shipping-class",
  },
};

export default BACKEND_URLS;
