export const TRANSACTION_TYPE_OPTIONS = [
  { label: "General / Alert", value: "alert" },
  { label: "Airtime", value: "airtime" },
  { label: "Data", value: "data" },
  { label: "Cable TV", value: "cable_tv" },
  { label: "Electricity", value: "electricity" },
  { label: "Betting", value: "betting" },
  { label: "Education", value: "education" },
  { label: "Airtime PIN", value: "airtime_epin" },
  { label: "Data PIN", value: "data_epin" },
  { label: "International Airtime", value: "internationalairtime" },
  { label: "International Data", value: "internationaldata" },
  { label: "Crypto", value: "crypto" },
  { label: "Crypto Buy", value: "crypto_purchase" },
  { label: "Crypto Sell", value: "crypto_sale" },
  { label: "Giftcard", value: "giftcard" },
  { label: "Giftcard Buy", value: "gift_card_purchase" },
  { label: "Giftcard Sell", value: "gift_card_sale" },
  { label: "Wallet Transfer", value: "wallet_transfer" },
  { label: "Wallet Credit", value: "wallet_credit" },
  { label: "Wallet Debit", value: "wallet_debit" },
  { label: "Withdrawal", value: "withdrawal" },
  { label: "Deposit", value: "deposit" },
  { label: "Refund", value: "refund" },
  { label: "Flight", value: "flight" },
  { label: "Hotel", value: "hotel" },
];
